name: Build and Publish package
on:
  push:
    tags:
      - 'msf-release-[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build-publish-package:
    name: Build and Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean install

      - name: Set OMOD name and Release version
        run: |
          OMOD_PATH=$(ls -1 omod/target/*.omod)
          OMOD_NAME=$(basename "$OMOD_PATH" .omod)
          RELEASE_VERSION=$(echo $GITHUB_REF_NAME | cut -d '-' -f 3)
          echo "OMOD_NAME=${OMOD_NAME}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_LITE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BAHMNI_LITE_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.BAHMNI_LITE_AWS_REGION }}

      - name: Upload OMOD
        run: aws s3 cp omod/target/${{env.OMOD_NAME}}.omod s3://stable/$GITHUB_REF_NAME/${{env.OMOD_NAME}}-${{env.RELEASE_VERSION}}.omod --region ${{ secrets.BAHMNI_LITE_AWS_REGION }} --acl public-read