name: Build and Publish package
on:
  push:
    branches: [ocp-dev-bahmni-lite, master]

jobs:
  build-publish-package:
    name: Build and Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean install
      - name: set Omod name
        run: echo "OMOD_NAME=$(basename "$(ls -1 omod/target/*.omod)" .omod)" >> $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_LITE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BAHMNI_LITE_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.BAHMNI_LITE_AWS_REGION }}
      - name: upload omod
        run: |
          aws s3 cp omod/target/${{env.OMOD_NAME}}.omod s3://v2-artefacts/${{github.event.repository.name}}/build/${{env.OMOD_NAME}}-$GITHUB_RUN_NUMBER.omod --region ${{ secrets.BAHMNI_LITE_AWS_REGION }} --acl public-read
          aws s3 rm s3://v2-artefacts/${{github.event.repository.name}}/latest/ --region ap-south-1 --recursive
          aws s3 cp omod/target/${{env.OMOD_NAME}}.omod s3://v2-artefacts/${{github.event.repository.name}}/latest/${{env.OMOD_NAME}}-$GITHUB_RUN_NUMBER.omod --region ${{ secrets.BAHMNI_LITE_AWS_REGION }} --acl public-read